### PR TITLE
Code Refactoring

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
- Fixed benchmark path
- Added editorconfig
- Refactored js / c++ code
- Formatted gyp config
- Simplified filenames

*Still passes all tests obviously.*

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
@confused-Techie I at least refactored the code, 
not sure what parts need to be made context aware.

I went with the Kelvin Henney approach of first
correcting, then deleting something or in this
case, refactoring then updating.

**Comment by confused-Techie** [comment]
Thanks a ton for contributing!

So I'll be happy to review this when I can.

But couple of notes:

* I'd probably remove the editor config, as that isn't a standard we have set on any other repo and am not sure if it's one that we want to start adding unnecessarily.
* Additionally while I think renaming files and such may be a good idea here, renaming the files AND refactoring all of the code makes this extremely difficult to review the PR. I have zero way to tell what you've changed here without reading everything line by line. I'd really recommend, for the future, splitting this PR up where we have the renames as their own PR with zero content changes. But do appreciate that at a glance it looks like you've kept the renames to a single commit, and I can use that to review.

Otherwise do appreciate this, and as for making this context aware that's likely a complete rewrite of all C++ code here. Which as I'm not exactly skilled or very familiar with C++ I'd be hard pressed to point out specific locations on where that needs to happen.

But since it looks like you may be familiar with the language NodeJS's website has many guides of how a functional Context-Aware module works, and some of the restrictions placed. So really finding those restrictions within the C++ code and writing them to by context aware and memory safe would be the only way to do so.

Lots of notes I know, sorry about that. But again really do appreciate your contribution! I'll try to review it tomorrow when I have more time after work.

**Comment by ElectronicsArchiver** [comment]
> I'd probably remove the editor config, as that isn't a standard we have set on any other repo and am not sure if it's one that we want to start adding unnecessarily.

I'd argue it's something that every repository on GitHub should have, 
it's the simplest way of having a common standard for the 'small' things.

Every notable IDE supports it as well.

Comparibly I wouldn't ever add a prettier file for example, since that
enforces styles that don't even cover all cases and often result in the
opposite, ugly, less readable code.

> Additionally while I think renaming files and such may be a good idea here, renaming the files AND refactoring all of the code makes this extremely difficult to review the PR. I have zero way to tell what you've changed here without reading everything line by line. I'd really recommend, for the future, splitting this PR up where we have the renames as their own PR with zero content changes. But do appreciate that at a glance it looks like you've kept the renames to a single commit, and I can use that to review.

Sure, like you said, I thought you would look at the individual 
commits as they are mostly on a per-file / file-pair basis.

**Comment by ElectronicsArchiver** [comment]
@confused-Techie So, did you take a look at it?

**Comment by ElectronicsArchiver** [comment]
@confused-Techie Any update?

**Comment by mauricioszabo** [comment]
Well... this PR basically changes all code...

So, I'm not sure why this PR exists. I honestly see the difference in coding style a downgrade. For example:

previously:
```cpp
  hasGAnchor = false;
  for (size_t pos = 0, len = source.size(); pos < len; pos++) {
    if (source[pos] == '\\' && pos + 1 < len) {
      if (source[pos + 1] == 'G') {
        hasGAnchor = true;
        break;
      }
      pos++;
    }
  }
```

Refactored:
```cpp
	hasGAnchor = false;

	const size_t length =
		source.size();

	for ( size_t index = 0 ; index < length ; index++ ){

		if( source[ index ] != '\\' )
			continue;

		if( index + 1 >= length )
			continue;

		if( source[ index + 1 ] == 'G'){
			hasGAnchor = true;
			break;
		}

		index++;
	}
```

**Comment by mauricioszabo** [comment]
Also, why `Library.js` was added?

**Comment by ElectronicsArchiver** [comment]
How do you call less nesting, separated initialization and spaced code worse ..

Lol, `Library.js` wasn't added, it was renamed.
`oniguruma.js` -> `Library.js`, following the
strategy of making code entrypoints generic 
names the same as you do for `index.js`, `mod.ts`, ..

**Comment by Daeraxa** [comment]
> How do you call less nesting, separated initialization and spaced code worse ..

Personally I find it much harder to read that way. The `if( ` vs `if (` in particular just looks... weird and I can't say I'm a fan of tabs vs spaces (I know its the age old discussion but still).

Also changes to coding style should be discussed first to see if we want to change the style at all and if so what we actually would want to use.

As for editorconfig, Pulsar doesn't even use it without a package (https://github.com/sindresorhus/atom-editorconfig) so I don't think it makes any sense at all to include it if Pulsar can't even read it. There is a discussion to be had to maybe look at including this kind of functionality by default in which case we would need to agree what the content of the editorconfig would even be to keep it standardised cross repo.

Also the fact that every file has been renamed *and* changed makes it really hard to review the PR. Ideally those would take place in different steps to give people a chance to actually review what changes were made.

**Comment by mauricioszabo** [comment]
Sorry folks, but this PR:

1. Renames almost every file
2. Almost doubles the number of lines
3. Break file naming and coding style that other packages' use
4. Changes coding style to some unknown standard (never saw the spaces before and between arguments but not before brackets) that's also inconsistent with itself
5. Address multiple issues in the same PR instead of making smaller changes each for every issue
6. Have some opinion-based decisions like adding editor config, tabs, file renames, and avoiding an automated tool
7. Does not solve any real issue, with the exception of the right benchmark.

So, I'll close this. We can discuss more about editorconfig file, coding style, on discussions or on discord (as these are all opinion-based) and we can open a more scoped PR to fix the benchmark, maybe even cherry-picking the right commit.

**Pull request closed without merging**
